### ISSUE TITLE
Fix komatiitic lava.

### ISSUE THREAD

**Issue by Anaghold** [EversongMill/Genesis#90]
Here is the problem: http://i.imgur.com/PJuMpU7.png

**Comment by crazysnailboy** [comment]
Fluid models rendering with gaps was a known issue that was fixed in Forge 1.11.2-13.20.0.2279.
The fix takes code from Forge pull request #3747, which resolves Forge bug #2993, and applies it to BlockKomatiiticLava.

This fix will not be necessary once the mod moves to or past 1.11.2.

See:
* http://www.minecraftforge.net/forum/topic/57885-1102-issues-with-custom-fluids/
* https://github.com/MinecraftForge/MinecraftForge/issues/2993
* https://github.com/MinecraftForge/MinecraftForge/pull/3747
